---
title: "Untitled"
format: html
editor: visual
---


## sf = 0.9, tf

```{r}
kiss_2010_scrap <- scrap_fun("../data_scrap/2010 Kiss.csv",
                             log_y = FALSE,
                             sf = c(.25, .5, 1, 2, 4), 
                             control = c("upper", "lower"), 
                             patient = c("upper", "lower")) |> 
  mutate(tf = 0) |> 
  relocate(tf, .after = sf)
```

```{r}
kiss_2010_long <- kiss_2010_scrap |> 
  estimate_se(eb = "ci", 
                ns = c(tabl |> filter(study == "2010 Kiss") |> 
                         pluck ("n_control") |> pluck(1), 
                   tabl |> filter(study == "2010 Kiss") |> 
                     pluck ("n_patient") |> pluck(1))) 
```

```{r}
kiss_2010_long_plot <- kiss_2010_long |> 
  mutate(across(c(m, se, sd, lower, upper), ~ 10 ^.x))
```

```{r}
kiss_2010 <- kiss_2010_long |> 
  calculate_es(sf)

kiss_2010
```

```{r}
save(kiss_2010, file = "../RData/kiss_2010.RData")
save(kiss_2010_long, file = "../RData/kiss_2010_long.RData")
save(kiss_2010_long_plot, file = "../RData/kiss_2010_long_plot.RData")
```
