---
title: "Untitled"
format: html
editor: visual
---

```{r}
cadenhead_2013_scrap <- scrap_fun("../data_scrap/2013 Cadenhead.csv",
                             sf = 1.22, 
                             control = c("upper", "lower"), 
                             patient = c("upper", "lower")) |> 
  mutate(tf = 8.33) |> 
  relocate(tf, .after = sf)
```

```{r}
cadenhead_2013_long <- estimate_se(cadenhead_2013_scrap, 
            eb = "se", 
            ns = c(tabl |> filter(study == "2013 Cadenhead") |> pluck ("n_control"), 
                   tabl |> filter(study == "2013 Cadenhead") |> pluck ("n_patient")))

cadenhead_2013 <- cadenhead_2013_long |> 
  calculate_es(sf)

cadenhead_2013
```

```{r}
cadenhead_2013_long_plot <- cadenhead_2013_long |> 
  mutate(across(c(m, se, sd, lower, upper), ~ 10^.x))
```

```{r}
save(cadenhead_2013_long, file = "../RData/cadenhead_2013_long.RData")
save(cadenhead_2013_long_plot, file = "../RData/cadenhead_2013_long_plot.RData")
save(cadenhead_2013, file = "../RData/cadenhead_2013.RData")
```
