---
title: "Untitled"
format: html
editor: visual
---

```{r}
fernandes_2018_scrap <- scrap_fun("../data_scrap/2018 Fernandes.csv",
                             log_y = FALSE,
                             sf = c(.2, .6, 1, 2, 5, 10, 20), 
                             control = c("upper", "lower"), 
                             patient = c("upper", "lower")) |> 
  mutate(tf = 0) |> 
  relocate(tf, .after = sf)
```

```{r}
fernandes_2018_long <- fernandes_2018_scrap |> 
    estimate_se(eb = "se", 
               ns = c(tabl |> filter(study == "2018 Fernandes") |> 
                        pluck ("n_control") |> pluck(1), 
                      tabl |> filter(study == "2018 Fernandes") |> 
                        pluck ("n_patient") |> pluck(1)))
```

```{r}
fernandes_2018_long_plot <- fernandes_2018_long |> 
  mutate(across(c(m, se, sd, lower, upper), ~ 10 ^.x))
```

```{r}
fernandes_2018 <- fernandes_2018_long |> 
  calculate_es(sf)
```

```{r}
save(fernandes_2018_long, file = "../RData/fernandes_2018_long.RData")
save(fernandes_2018_long_plot, file = "../RData/fernandes_2018_long_plot.RData")
save(fernandes_2018, file = "../RData/fernandes_2018.RData")
```
