---
title: "Untitled"
format: html
editor: visual
---

```{r}
zemon_2021_scrap_short_dur <- scrap_fun("../data_scrap/2021 Zemon short dur.csv",
                             sf = c(.5, 1, 4, 7, 21), 
                             control = c("upper", "lower"), 
                             patient = c("upper", "lower")) |> 
  mutate(tf = 0) |> 
  relocate(tf, .after = sf)
```

```{r}
zemon_2021_long_short_dur <- zemon_2021_scrap_short_dur |> 
  estimate_se(eb = "iqr", 
               ns = c(tabl |> filter(study == "2021 Zemon") |> 
                        pluck ("n_control"), 
                      tabl |> filter(study == "2021 Zemon") |> 
                        pluck ("n_patient")))

zemon_2021_short_dur <- zemon_2021_long_short_dur |> 
  calculate_es(sf)

zemon_2021_short_dur
```

```{r}
zemon_2021_long_plot_short_dur <- zemon_2021_long_short_dur |> 
  mutate(across(c(m, se, sd, lower, upper), ~ 10 ^.x))
```

```{r}
save(zemon_2021_long_plot_short_dur, file = "../RData/zemon_2021_long_plot_short_dur.RData")
save(zemon_2021_long_short_dur, file = "../RData/zemon_2021_long_short_dur.RData")
save(zemon_2021_short_dur, file = "../RData/zemon_2021_short_dur.RData")
```
