---
title: "Untitled"
format: html
editor: visual
---

```{r}
shoshina_2021b_sf_05_long <- tibble(study = "2021b Shoshina", 
                                   sf = .5, 
                                   cond = c("control", "patient"),
                                   m = c(17.8, 12.06), 
                                   sd = c(5.3, 5.3), 
                                   n = c(tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_control"),
                                         tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_patient"))) 

shoshina_2021b_sf_25_long <- tibble(study = "2021b Shoshina", 
                                   sf = 2.5, 
                                   cond = c("control", "patient"),
                                   m = c(21.4, 12.6), 
                                   sd = c(8.1, 5.5), 
                                   n = c(tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_control"),
                                         tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_patient"))) 

shoshina_2021b_sf_10_long <- tibble(study = "2021b Shoshina", 
                                   sf = 10, 
                                   cond = c("control", "patient"),
                                   m = c(7.9, 4.2), 
                                   sd = c(4.6, 2.9), 
                                   n = c(tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_control"),
                                         tabl |> filter(study == "2021b Shoshina") |> 
                                           pluck ("n_patient"))) 



shoshina_2021b_long <- shoshina_2021b_sf_05_long |> 
  bind_rows(shoshina_2021b_sf_25_long) |> 
  bind_rows(shoshina_2021b_sf_10_long) |> 
  mutate(se = sd / sqrt(n), 
         lower = m - se, 
         upper = m + se) |> 
  mutate(tf = 0) |> 
  relocate(tf, .after = sf)

shoshina_2021b_long |>
  ggplot(aes(x = sf, y = m, ymin = lower, ymax = upper, color = cond)) +
  geom_pointrange() +
  geom_line()
```

```{r}
shoshina_2021b <- shoshina_2021b_long |> 
  calculate_es(sf)
```

```{r}
save(shoshina_2021b_long, file = "../RData/shoshina_2021b_long.RData")
save(shoshina_2021b, file = "../RData/shoshina_2021b.RData")
```
