---
title: "Untitled"
format: html
editor: visual
---

```{r}
qian_2022_scrap_short_dur <- scrap_fun("../data_scrap/2022 Qian short dur.csv",
                                 log_y_plot = FALSE,
                                 sf = c(.56, 4.5, 11),
                                 control = c("upper", "lower"), 
                                 patient = c("upper", "lower")) |> 
  mutate(tf = 0) |> 
  relocate(tf, .after = sf)
```

```{r}
qian_2022_long_short_dur <- qian_2022_scrap_short_dur |> 
  estimate_se(eb = "se", 
              ns = c(tabl |> filter(study == "2022 Qian") |> 
                        pluck ("n_control"), 
                      tabl |> filter(study == "2022 Qian") |> 
                        pluck ("n_patient")))

qian_2022_short_dur <- qian_2022_long_short_dur |> 
  calculate_es(sf)

qian_2022_short_dur
```

```{r}
save(qian_2022_long_short_dur, file = "../RData/qian_2022long_short_dur.RData")
save(qian_2022_short_dur, file = "../RData/qian_2022_short_dur.RData")
```
