---
title: "Untitled"
format: html
editor: visual
---

## Contrast senstivity across studies

```{r}
studies_long_plot <- list(schwartz_1985_long, 
                     schwartz_1987_long, 
                     slaghuis_1998_long_plot,
                     chen_1999_long,
                     keri_2000_long_plot, 
                     keri_2002_long_plot, 
                     chen_2003_a_long_plot,
                     chen_2003_b_long_plot,
                     chen_2004_long_plot,
                     sheremata_2004_long_plot,
                     keri_2004_long_plot,
                     butler_2005_long,
                     revheim_2006_long,
                     cimmer_2006_long_plot,
                     chen_2006_long_plot,
                     odonnell_2006_long_plot, 
                     butler_2008_long,
                     norton_2008_long,
                     butler_2009_long, 
                     kantrowitz_2009_long,
                     norton_2009_long_plot,
                     brittain_2010_long_plot,
                     kiss_2010_long_plot,
                     chen_2011_long_plot,
                     kelemen_2013_long,
                     halasz_2013_long,
                     cadenhead_2013_long_plot,
                     calderone_2013_long,
                     nogueira_2013_long,
                     martinez_2013_long,
                     serrano_2014_long,
                     shoshina_2014_long, 
                     carter_2017_long,
                     fernandes_2018_long_plot, 
                     fernandes_2019_long,
                     zemon_2021_long_plot,
                     shoshina_2021a_long,
                     shoshina_2021b_long, 
                     qian_2022_long,
                     kadivar_2024_long_plot) |> 
  map_df(bind_rows) |> 
  ungroup() |> 
  mutate(cond = if_else(cond == "patient", LABEL_SCZ, LABEL_CONTROL)) 

```

## Effect size across studies

```{r}
studies_es <- list(schwartz_1985, 
                   schwartz_1987, 
                   slaghuis_1998,
                   chen_1999, 
                   keri_2000, 
                   keri_2002, 
                   chen_2003_a, 
                   chen_2003_b,
                   chen_2004,
                   sheremata_2004,
                   keri_2004,
                   butler_2005,
                   bidwell_2006,
                   revheim_2006,
                   cimmer_2006,
                   chen_2006,
                   odonnell_2006, 
                   martinez_2008,
                   butler_2008,
                   norton_2008,
                   butler_2009,
                   kantrowitz_2009,
                   norton_2009,
                   brittain_2010,
                   kiss_2010, 
                   chen_2011,
                   dias_2011, 
                   kelemen_2013,
                   halasz_2013,
                   lima_2013,
                   cadenhead_2013,
                   calderone_2013,
                   nogueira_2013,
                   martinez_2013,
                   serrano_2014,
                   shoshina_2014, 
                   maher_2016a,
                   maher_2016b,
                   carter_2017,
                   fernandes_2018, 
                   fernandes_2019,
                   zemon_2021,
                   shoshina_2021a,
                   shoshina_2021b, 
                   qian_2022,
                   kadivar_2024) |> 
  map_df(bind_rows) |> 
  ungroup() |> 
  mutate(study = fct_rev(study), 
         study_id = paste(study, sf, tf, sep = "_")) |> 
  relocate(study_id, .before = "study") |> 
  left_join(tabl |> select(study, p_med), by = join_by(study)) |> 
  left_join(tabl |> select(study, p_gender), by = join_by(study)) |> 
  left_join(tabl |> select(study, cpz), by = join_by(study)) |> 
  left_join(tabl |> select(study, sd_cpz), by = join_by(study)) |> 
  left_join(tabl |> select(study, duration), by = join_by(study)) |> 
  left_join(tabl |>  select(study, dur_illness), by = join_by(study)) |> 
  left_join(tabl |> select(study, BPRS), by = join_by(study)) |> 
  left_join(tabl |> select(study, PANSS_N), by = join_by(study)) |> 
  left_join(tabl |> select(study, PANSS_P), by = join_by(study)) |> 
  left_join(tabl |> select(study, PANSS_GP), by = join_by(study)) |>
  left_join(tabl |> select(study, method), by = join_by(study)) |>
  left_join(tabl |> select(study, size), by = join_by(study)) |>
  left_join(tabl |> select(study, ecc), by = join_by(study)) |>
  left_join(tabl |> select(study, luminance), by = join_by(study)) |>
  left_join(tabl |> select(study, dv), by = join_by(study)) |>
  left_join(tabl |> select(study, ses_control, ses_patient), by = join_by(study)) |>
  left_join(tabl |> select(study, years_control, years_patient), by = join_by(study)) |>
  left_join(tabl |> select(study, task), by = join_by(study)) |>
  mutate(full_panss = (!is.na(PANSS_N) & !is.na(PANSS_P) & !is.na(PANSS_GP)),
         PANSS_T = if_else(full_panss, PANSS_N + PANSS_P + PANSS_GP, NA),
         PANSS_from_BPRS = brps_to_panss_fun(BPRS),
         panss_t_meta = if_else(!is.na(PANSS_T), PANSS_T, PANSS_from_BPRS)) 
```

## Contrast sensitivity plot

```{r}
studies_long_p_cs_plot <- studies_long_plot |> 
  mutate(tf_str = paste(tf, "Hz")) |> 
  mutate(tf_str = fct_reorder(tf_str, tf)) |> 
  group_by(study, cond, tf) |> 
  mutate(n = n())

p_cs <-  ggplot() +
  facet_wrap(vars(study, tf_str), scales = "free", ncol = 6, 
             labeller = labeller(tf_str = label_value)) +
  geom_pointrange(data = studies_long_p_cs_plot, 
                  aes(x = sf, y = m, ymin = lower, ymax = upper, 
                      shape = cond, color = cond),
                  size = SIZE_POINT_RANGE, 
                  position = position_dodge(width = .1)) +
  geom_line(data = studies_long_p_cs_plot |> 
              filter(n > 1),
            aes(x = sf, y = m, color = cond),
            position = position_dodge(width = .1)) +
  labs(x = LABEL_SPATIAL_FREQUENCY, y = LABEL_CONTRAST_SENSITIVITY) +
  scale_x_log10(breaks = c(.3, 1, 3, 10), 
                limits = c(.2, 12),
                labels =  c("0.3", "1", "3", "10")) +
  scale_y_log10(breaks = log_breaks(5)) +
  theme_classic(9) +
  theme(legend.position = c(.9, .03), 
        legend.title = element_blank(), 
        axis.line = element_line(linewidth = WIDTH_AXIS),
        axis.ticks = element_line(linewidth = WIDTH_AXIS),
        strip.background = element_blank(), 
        strip.text.x = element_text(hjust = 0, 
                                    margin = margin(0, 0, 3, 0)),
        panel.spacing.y = unit(LENGTH_PANEL_SPACING_Y, "lines"))

ggsave("figures/paper/sup/p_cs.pdf", p_cs, width = 7.2, height = 13.5)

ggsave("figures/paper/sup/p_cs.png", p_cs, width = 7.2, height = 13.5)
```

## Effect size plot

```{r}
studies_es_p_es_plot <- studies_es |> 
  filter(!(study %in% studies_no_sf)) |> # because there were not details to compute SF 
  mutate(tf_str = paste(tf, "Hz")) |> 
  mutate(tf_str = fct_reorder(tf_str, tf)) |> 
  group_by(study, tf) |> 
  mutate(n = n())

p_es <- ggplot() +
  facet_wrap(vars(study, tf_str), ncol = 7, scales = "free", 
             labeller = labeller(tf = label_value)) +
  geom_hline(yintercept = 0, lty = 2, linewidth = WIDTH_AXIS) +
  geom_pointrange(data = studies_es_p_es_plot,
                  aes(x = sf, y = es, ymin = ci.lo, ymax = ci.hi), 
                  size = SIZE_POINT_RANGE * 0.7, color = SINGLE_COLOR) +
  geom_line(data = studies_es_p_es_plot |> 
              filter(n > 1),
            aes(x = sf, y = es),
              color = SINGLE_COLOR) +
  labs(x = LABEL_SPATIAL_FREQUENCY, y = LABEL_EFFECT_SIZE) +
  scale_x_log10(breaks = c(.3, 1, 3, 10), 
                 limits = c(.2, 12),
                     labels =  c("0.3", "1", "3", "10")) +
  scale_y_continuous(breaks = breaks_pretty(4)) +
  theme_classic(9) +
  theme(legend.position = c(.8, .05), 
        legend.title = element_blank(), 
        axis.line = element_line(linewidth = WIDTH_AXIS),
        axis.ticks = element_line(linewidth = WIDTH_AXIS),
        strip.background = element_blank(), 
        strip.text.x = element_text(hjust = 0, 
                                    margin = margin(0, 0, 3, 0)),
        panel.spacing.y = unit(LENGTH_PANEL_SPACING_Y, "lines"))

ggsave("figures/paper/sup/p_es.pdf", p_es, width = 7.5, height = 11.5)

ggsave("figures/paper/sup/p_es.png", p_es, width = 7.5, height = 11.5)
```

## Contrast sensitivity plot. One plot.

```{r}
p_cs_one_plot <- studies_long_plot |> 
  mutate(tf = paste(tf, "Hz")) |> 
  filter(study == "1985 Schwartz") |> 
  ggplot(aes(x = sf, y = m, ymin = lower, ymax = upper, 
             shape = cond, color = cond)) +
  facet_wrap(vars(study, tf), scales = "free_y", ncol = 6, 
             labeller = labeller(tf = label_value)) +
  geom_pointrange(size = SIZE_POINT_RANGE, 
                  position = position_dodge(width = .075)) +
  geom_line(position = position_dodge(width = .075)) +
  labs(x = LABEL_SPATIAL_FREQUENCY, y = LABEL_CONTRAST_SENSITIVITY) +
  scale_x_log10(breaks = c(.3, 1, 3, 10),
                     labels =  c("0.3", "1", "3", "10")) +
  scale_y_log10(breaks = log_breaks(5)) +
  theme_classic(7) +
  theme(legend.title = element_blank(), 
        strip.background = element_blank(), 
        axis.line = element_line(linewidth = WIDTH_AXIS),
        axis.ticks = element_line(linewidth = WIDTH_AXIS),
        strip.text.x = element_text(hjust = 0, 
                                    margin = margin(0, 0, 3, 0)),
        panel.spacing.y = unit(LENGTH_PANEL_SPACING_Y, "lines"))

p_cs_one_plot
```

## Effect size plot. One plot.

```{r}
p_es_one_plot <- studies_es |> 
  mutate(tf = paste(tf, "Hz")) |> 
  filter(study == "1985 Schwartz") |> 
  ggplot(aes(x = sf, y = es, ymin = ci.lo, ymax = ci.hi)) +
  facet_wrap(vars(study, tf), ncol = 6, scales = "free_y", 
             labeller = labeller(tf = label_value)) +
  geom_hline(yintercept = 0, lty = 2, linewidth = WIDTH_AXIS) +
  geom_pointrange(size = SIZE_POINT_RANGE * 0.7, color = SINGLE_COLOR) +
  geom_line(color = SINGLE_COLOR) +
  labs(x = LABEL_SPATIAL_FREQUENCY, y = LABEL_EFFECT_SIZE) +
  scale_x_log10(breaks = c(.3, 1, 3, 10), 
                     labels =  c("0.3", "1", "3", "10")) +
  scale_y_continuous(breaks = extended_breaks(n = 3)) +
  theme_classic(7) +
  theme(legend.position = c(.8, .05), 
        legend.title = element_blank(), 
        axis.line = element_line(linewidth = WIDTH_AXIS),
        axis.ticks = element_line(linewidth = WIDTH_AXIS),
        strip.background = element_blank(), 
        strip.text.x = element_text(hjust = 0, 
                                    margin = margin(0, 0, 3, 0)),
        panel.spacing.y = unit(LENGTH_PANEL_SPACING_Y, "lines"))

p_es_one_plot
```

## Figure one plot

```{r}
p_stim <- ggdraw() + draw_image(x = 0, y = -0.1, scale = .85,
                                "figures/paper/stimulus.png")
p_example_study <- plot_grid(
  p_stim,
  p_cs_one_plot, 
  p_es_one_plot, 
  rel_widths = c(.4, .37, .23), nrow = 1, labels = "AUTO")

ggsave("figures/paper/p_example_study.pdf", p_example_study, 
       width = 5.9, height = 1.58)

ggsave("figures/paper/p_example_study.png", p_example_study, 
       width = 5.9, height = 1.58)
```
