---
title: "Untitled"
format: html
editor: visual
---

## Three-level meta-analysis

```{r}
studies_es_chronic_short_dur <- studies_es_short_dur |> 
    filter(!(study %in% c("2021a Shoshina", "2010 Kiss")))
  
meta_all_samples_short_dur <- rma.mv(yi = es, 
                   V = var, 
                   slab = study,
                   data = studies_es_chronic_short_dur,
                   random = ~ 1 | study/study_id, 
                   test = "t", 
                   method = "REML")

meta_all_samples_short_dur
```

```{r}
meta_all_samples_short_dur$pval
```




## Subgroup Analyses

```{r}
meta_all_samples_sf_short_dur <- rma.mv(yi = es, 
                   V = var, 
                   slab = study,
                   data = studies_es_chronic_short_dur,
                   random = ~ 1 | study/study_id, 
                   test = "t", 
                   method = "REML", 
                   mods = ~ sf)

meta_all_samples_sf_short_dur 
```

```{r}
meta_all_samples_tf_short_dur <- rma.mv(yi = es, 
                   V = var, 
                   slab = study,
                   data = studies_es_chronic_short_dur,
                   random = ~ 1 | study/study_id, 
                   test = "t", 
                   method = "REML", 
                   mods = ~ tf)

meta_all_samples_tf_short_dur
```



