---
title: "Untitled"
format: html
editor: visual
---

## Three-level meta-analysis

```{r}
studies_es_chronic_short_dur <- studies_es_short_dur |> 
      filter(!(study %in% c("2021a Shoshina", "2010 Kiss", "2024 Kadivar"))) |> 
  anti_join(studies_es_without_sf)
  
meta_all_samples_short_dur <- rma.mv(yi = es, 
                   V = var, 
                   slab = study,
                   data = studies_es_chronic_short_dur,
                   random = ~ 1 | study/study_id, 
                   test = "t", 
                   method = "REML")

meta_all_samples_short_dur
```

```{r}
rma.mv(yi = es, 
       V = var, 
       slab = study,
       data = studies_es_chronic_short_dur,
       random = ~ 1 | study/study_id, 
       test = "t", 
       method = "REML", 
       mods = ~ sf)
```

```{r}
rma.mv(yi = es, 
       V = var, 
       slab = study,
       data = studies_es_chronic_short_dur,
       random = ~ 1 | study/study_id, 
       test = "t", 
       method = "REML", 
       mods = ~ tf)
```
