---
title: "Untitled"
format: html
editor: visual
---

```{r}
table_cpz_chronic <- create_table_moderator(meta_one_sample_chronic_cpz, "CPZ") 

table_p_med_chronic <- create_table_moderator(meta_one_sample_chronic_p_med, "Prop. medicated") 

table_illness_dur_chronic <- create_table_moderator(meta_one_sample_chronic_dur_illness, "Illness duration") 

table_illness_p_gender_chronic <- create_table_moderator(meta_one_sample_chronic_p_gender, "Patient gender") 

table_illness_size_chronic <- create_table_moderator(meta_one_sample_chronic_size, "Stimulus size") 

table_illness_luminance_chronic <- create_table_moderator(meta_one_sample_chronic_luminance, "Luminance") 

table_illness_duration_chronic <- create_table_moderator(meta_one_sample_chronic_duration, "Stimulus duration") 

table_illness_ecc_chronic <- create_table_moderator(meta_one_sample_chronic_ecc, "Eccentricity") 

table_panss_chronic <- create_table_moderator(meta_one_sample_chronic_panss, "PANSS total") 



table_sf <- create_table_moderator(meta_all_samples_sf, "Spatial frequency") 

table_tf <- create_table_moderator(meta_all_samples_tf, "Temporal frequency") 

table_cpz_all <- create_table_moderator(meta_all_samples_cpz, "CPZ ") 

table_moderators <- table_cpz_chronic |> 
  bind_rows(table_p_med_chronic) |> 
  bind_rows(table_illness_dur_chronic) |> 
  bind_rows(table_panss_chronic) |> 
  bind_rows(table_illness_p_gender_chronic) |> 
  bind_rows(table_illness_size_chronic) |> 
  bind_rows(table_illness_duration_chronic) |> 
  bind_rows(table_illness_luminance_chronic) |> 
  bind_rows(table_illness_ecc_chronic) |> 

  bind_rows(table_sf) |> 
  bind_rows(table_tf) |> 
  bind_rows(table_cpz_all) |>
  gt() |> 
    cols_align("center") |> 
      tab_row_group(
    label = "Using all samples from each study",
    rows = moderator %in% c("Spatial frequency", "Temporal frequency",
    "CPZ ")) |>
    tab_row_group(
    label = "Using one sample from each study",
    rows = moderator %in% c("CPZ", "Prop. medicated", "PANSS total", 
                            "Illness duration", "Patient gender", 
                            "Stimulus size", "Stimulus duration",
                            "Luminance", "Eccentricity")) |> 

  tab_spanner(
    label = "Intercept", 
    columns = c(estimate_intercept, statistic_intercept, p.value_intercept, ci_intercept)) |> 
  tab_spanner(
    label = "Slope", 
    columns = c(estimate_slope, statistic_slope, p.value_slope, ci_slope)) |> 
  cols_move(
    columns = ci_intercept,
    after = estimate_intercept) |> 
    cols_move(
    columns = ci_slope,
    after = estimate_slope) |>
  cols_label(
    moderator = "variable",
    n_samples = "# samples",
    estimate_intercept = "Estimate",
    ci_intercept = "95% CI",
    statistic_intercept = "t",
    p.value_intercept = "P",
    estimate_slope = "Estimate",
    ci_slope = "95% CI",
    statistic_slope = "t",
    p.value_slope = "P"
    ) |> 
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.size = 14)


table_moderators

gtsave(table_moderators, "figures/paper/table_moderators.png")


save(table_moderators, file = "RData/table_moderators.RData")
```


### Supplementary table

```{r}
table_cpz <- create_table_moderator(meta_one_sample_cpz, "CPZ") 

table_p_med <- create_table_moderator(meta_one_sample_p_med, "Prop. medicated") 

table_moderators_sup <- table_cpz |> 
  bind_rows(table_p_med) |> 
  gt() |> 
    cols_align("center") |> 
    #   tab_row_group(
    # label = "Using all samples from each study",
    # rows = moderator %in% c("Spatial frequency", "Temporal frequency",
    # "CPZ ")) |>
    # tab_row_group(
    # label = "Using one sample from each study",
    # rows = moderator %in% c("CPZ", "Prop. medicated", "PANSS total", 
    #                         "Illness duration", "Patient gender", 
    #                         "Stimulus size", "Stimulus duration", "Eccentricity")) |> 

  tab_spanner(
    label = "Intercept", 
    columns = c(estimate_intercept, statistic_intercept, p.value_intercept, ci_intercept)) |> 
  tab_spanner(
    label = "Slope", 
    columns = c(estimate_slope, statistic_slope, p.value_slope, ci_slope)) |> 
  cols_move(
    columns = ci_intercept,
    after = estimate_intercept) |> 
    cols_move(
    columns = ci_slope,
    after = estimate_slope) |>
  cols_label(
    n_samples = "# samples",
    estimate_intercept = "Estimate",
    ci_intercept = "95% CI",
    statistic_intercept = "t",
    p.value_intercept = "P",
    estimate_slope = "Estimate",
    ci_slope = "95% CI",
    statistic_slope = "t",
    p.value_slope = "P"
    ) |> 
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.size = 14)


table_moderators_sup

gtsave(table_moderators_sup, "figures/paper/table_moderators_sup.png")

```

